[versions]
commons-math3 = "3.6.1"
guava = "32.1.3-jre"
junit-jupiter = "5.10.1"

[libraries]
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math3" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }